//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломный_проект
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class silverCinemaEntities : DbContext
    {
        public silverCinemaEntities()
            : base("name=silverCinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Билеты> Билеты { get; set; }
        public virtual DbSet<Время> Время { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Жанр> Жанр { get; set; }
        public virtual DbSet<Места> Места { get; set; }
        public virtual DbSet<Сеанс> Сеанс { get; set; }
        public virtual DbSet<Фильм> Фильм { get; set; }
    }
}
