//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломный_проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фильм
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фильм()
        {
            this.Сеанс = new HashSet<Сеанс>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public int Цена { get; set; }
        public string Возрастное_ограничение { get; set; }
        public string Длительность { get; set; }
        public int Id_Жанр { get; set; }
        public byte[] Постер { get; set; }
    
        public virtual Жанр Жанр { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сеанс> Сеанс { get; set; }
    }
}
